[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.116.1"}
psycopg = {extras = ["binary"], version = "^3.2.9"}
python-dotenv = "^1.1.1"
openai = "^1.99.9"
qdrant-client = "^1.15.1"
stripe = "^12.4.0"
firebase-admin = "^7.1.0"
pydantic-settings = "^2.10.1"
python-multipart = "^0.0.20"
sendgrid = "^6.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
